name: responsive_dashboard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/images/

  fonts:
  - family: Montserrat
    fonts:
    - asset: assets/fonts/Montserrat-Regular.ttf

flutter_assets:
  assets_path: assets/images
  output_path: lib/utils
  filename: app_images.dart
  field_prefix: null
